#!/bin/sh

SCRIPT_DIR=$(dirname $0)
CONFIGFILE="lib/config.js"
# Copy config.js to temp location
cp -rf $CONFIGFILE $SCRIPT_DIR/config.js

#update config file
sed -i '/^\/\/CIPHERCIPHERCIPHERCIPHERCIPHERCIPHERCIPHERCIPHER$/,$d' $CONFIGFILE
echo //CIPHERCIPHERCIPHERCIPHERCIPHERCIPHERCIPHERCIPHER$'\n' >> $CONFIGFILE

#remove config values
node $SCRIPT_DIR/removeConfigValues.js >> $CONFIGFILE